### ISSUE TITLE
Recupero messaggio da link url

### ISSUE THREAD

**Issue by ipersoft** [ipersoft/telegram_bot#1]

**Comment by ipersoft** [comment]
@olistik stavo pensando che non voglio far diventare troppo complicata la scrittura del json per il bot.
Lui deve solo prendere e rispondere.
In caso di cose complicate uno li fa a parte e poi li passa al bot come per il meteo

Pensavo di aggiungere un campo TextFromURL="www.meteo.it/now.php"

**Comment by olistik** [comment]
@ipersoft ci sta, l'aggiunta di un campo di controllo esterno come nel caso di `textFromURL` ti permette comunque di ottenere buona parte delle funzionalità che ti ho descritto nel caso di un map-reduce che si basa su una struttura complessa tipo:

``` json
{
  "id": "meteo",
  "_meta": [{
    "type": "url_fetch",
    "source": "http://www.meteo.it/get.php",
    "destination": "text"
  }, {
    "type": "format_conversion",
    "source": "text",
    "destination": "text",
    "format": "json"
  }]
}
```

L'unico inconveniente del tuo approccio è che in fase di implementazione ti costringe ad effettuare una catena di `if, elseif` per verificare la presenza degli attributi di controllo stile `TextFromURL` mentre nel caso dell'uso dell'attributo `type`, puoi effettuare un più comodo `switch`.

**Comment by ipersoft** [comment]
Teniamo per ora TextFromURL
